export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Credentials', true);
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS');
  res.setHeader(
    'Access-Control-Allow-Headers',
    'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version, Authorization'
  );

  if (req.method === 'OPTIONS') return res.status(200).end();

  const courses = [
    {
      id: 'TECH004',
      code: 'TECH004',
      title: 'Digital Tools for Industry 4.0',
      shortDescription: 'Explore Digital Transformation in Manufacturing Sector',
      domain: 'Technology',
      category: 'Industry 4.0',
      hours: 20,
      mode: 'online',
      price: 4999,
      finalPrice: 4999,
      status: 'PUBLISHED',
    },
    {
      id: 'TECH054',
      code: 'TECH054',
      title: 'Full Stack Development (Intermediate Level)',
      shortDescription: 'Master front-end and back-end skills to unlock limitless innovation',
      domain: 'Technology',
      category: 'Industry 4.0',
      hours: 20,
      mode: 'online',
      price: 4999,
      finalPrice: 4999,
      status: 'PUBLISHED',
    },
    {
      id: 'TECH067',
      code: 'TECH067',
      title: 'Electric Vehicle Battery Management',
      shortDescription: 'Comprehensive insights into EV battery packs, thermal management, and BMS architectures',
      domain: 'Technology',
      category: 'Electric Vehicles',
      hours: 25,
      mode: 'blended',
      price: 4999,
      finalPrice: 4999,
      status: 'PUBLISHED',
    },
    {
      id: 'TECH068',
      code: 'TECH068',
      title: 'Autonomous Driving & ADAS',
      shortDescription: 'LiDAR, radar fusion, computer vision and decision algorithms for autonomous mobility',
      domain: 'Technology',
      category: 'ADAS',
      hours: 30,
      mode: 'online',
      price: 4999,
      finalPrice: 4999,
      status: 'PUBLISHED',
    },
    {
      id: 'TECH061',
      code: 'TECH061',
      title: 'Cloud Architecture & DevOps',
      shortDescription: 'Design resilient microservices, CI/CD pipelines, and cloud native infrastructure',
      domain: 'Technology',
      category: 'Industry 4.0',
      hours: 25,
      mode: 'online',
      price: 4999,
      finalPrice: 4999,
      status: 'PUBLISHED',
    },
    {
      id: 'TECH032',
      code: 'TECH032',
      title: 'AI & Deep Learning Applications',
      shortDescription: 'Neural networks, transformer architectures and computer vision for industry',
      domain: 'Technology',
      category: 'Industry 4.0',
      hours: 30,
      mode: 'online',
      price: 4999,
      finalPrice: 4999,
      status: 'PUBLISHED',
    },
    {
      id: 'TECH041',
      code: 'TECH041',
      title: 'Industrial Robotics & Automation',
      shortDescription: 'PLC programming, robotic kinematics, industrial automation with SCADA and IoT',
      domain: 'Technology',
      category: 'Manufacturing',
      hours: 25,
      mode: 'blended',
      price: 4999,
      finalPrice: 4999,
      status: 'PUBLISHED',
    },
    {
      id: 'TECH015',
      code: 'TECH015',
      title: 'Renewable Energy Systems & Smart Grids',
      shortDescription: 'Solar PV, wind energy integration, and smart microgrid power electronics',
      domain: 'Technology',
      category: 'Renewable Energy',
      hours: 20,
      mode: 'online',
      price: 4999,
      finalPrice: 4999,
      status: 'PUBLISHED',
    },
    {
      id: 'TECH022',
      code: 'TECH022',
      title: 'Quantum Computing Foundations',
      shortDescription: 'Quantum algorithms, Qiskit programming and quantum cryptography principles',
      domain: 'Technology',
      category: 'Quantum Computing',
      hours: 20,
      mode: 'online',
      price: 4999,
      finalPrice: 4999,
      status: 'PUBLISHED',
    },
    {
      id: 'TECH055',
      code: 'TECH055',
      title: 'Structural Simulation & FEA',
      shortDescription: 'Finite element analysis, ANSYS multiphysics modeling, and structural optimization',
      domain: 'Technology',
      category: 'Simulation',
      hours: 20,
      mode: 'online',
      price: 4999,
      finalPrice: 4999,
      status: 'PUBLISHED',
    },
    {
      id: 'MGMT001',
      code: 'MGMT001',
      title: 'Supply Chain & Logistics Management',
      shortDescription: 'Lean operations, digital logistics, inventory optimization and procurement',
      domain: 'Management',
      category: 'Operations Management',
      hours: 20,
      mode: 'online',
      price: 4999,
      finalPrice: 4999,
      status: 'PUBLISHED',
    },
    {
      id: 'MGMT002',
      code: 'MGMT002',
      title: 'Corporate Finance & Valuation',
      shortDescription: 'Financial modeling, valuation analysis, risk assessment and corporate budgeting',
      domain: 'Management',
      category: 'Finance',
      hours: 20,
      mode: 'online',
      price: 4999,
      finalPrice: 4999,
      status: 'PUBLISHED',
    },
    {
      id: 'MGMT003',
      code: 'MGMT003',
      title: 'Strategic Marketing & Brand Management',
      shortDescription: 'Digital marketing strategies, market segmentation and customer lifetime value',
      domain: 'Management',
      category: 'Marketing',
      hours: 20,
      mode: 'online',
      price: 4999,
      finalPrice: 4999,
      status: 'PUBLISHED',
    },
    {
      id: 'MGMT004',
      code: 'MGMT004',
      title: 'Data Science for Business',
      shortDescription: 'Harness data science techniques to drive strategic business decisions',
      domain: 'Management',
      category: 'Data Science',
      hours: 30,
      mode: 'online',
      price: 4999,
      finalPrice: 4999,
      status: 'PUBLISHED',
    },
    {
      id: 'LEAD001',
      code: 'LEAD001',
      title: 'Leadership Excellence Program',
      shortDescription: 'Develop transformational leadership skills for the modern workplace',
      domain: 'Leadership & Personality',
      category: 'Leadership & Personality',
      hours: 20,
      mode: 'online',
      price: 4999,
      finalPrice: 4999,
      status: 'PUBLISHED',
    },
    {
      id: 'LEAD002',
      code: 'LEAD002',
      title: 'Communication & Personality Development',
      shortDescription: "Trainers lend their expertise to evaluate and enhance one's personality for better outcomes",
      domain: 'Leadership & Personality',
      category: 'Leadership & Personality',
      hours: 15,
      mode: 'online',
      price: 4999,
      finalPrice: 4999,
      status: 'PUBLISHED',
    },
    {
      id: 'LEAD003',
      code: 'LEAD003',
      title: 'Stress Management & Work-Life Balance',
      shortDescription: 'Build resilience and achieve sustainable high performance at work',
      domain: 'Leadership & Personality',
      category: 'Leadership & Personality',
      hours: 10,
      mode: 'online',
      price: 4999,
      finalPrice: 4999,
      status: 'PUBLISHED',
    },
  ];

  return res.status(200).json({
    success: true,
    total: courses.length,
    data: courses,
    courses,
  });
}
